- name: Install Maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven-setup

- name: SetUp Application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup
    
- name: Create /app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Change working directory to /app
  ansible.builtin.command: cd /app

- name: Install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: Rename jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: Load Schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mysql-schema

- name: Start application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup