    - name: Install Python and required packages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: installed
      loop:
        - python3
        - gcc
        - python3-devel

    - name: Check if roboshop user exists
      ansible.builtin.command: id roboshop
      register: roboshop_user
      ignore_errors: true

    - name: Create roboshop user if it doesn't exist
      ansible.builtin.user:
        name: roboshop
        state: present
        system: no
        shell: /bin/bash
        create_home: yes
      when: roboshop_user|failed

    - name: Ensure /app directory exists
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download payment and extract
      ansible.builtin.unarchive:
        src: https://roboshop-builds.s3.amazonaws.com/payment.zip
        dest: /app
        remote_src: yes

    - name: Install Python dependencies
      ansible.builtin.command: pip3 install -r /app/requirements.txt
      args:
        chdir: /app

    - name: Copy payment service unit file
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system/payment.service
      notify: Restart payment service