    - name: Enable Redis topic
      command: amazon-linux-extras enable redis4.0
    
    - name: Install Redis
      ansible.builtin.yum:
        name: redis
        state: present

    - name: Allow remote connections to redis
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
      when: "'/etc/redis.conf' is file"
  # Check if the file exists using the stat module

    - name: Start and enable redis
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes
