- name: Install EPEL repository (if not already installed)
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Install Node.js
  ansible.builtin.yum:
    name: nodejs
    state: present