- name: Install Node.js using curl and yum
  ansible.builtin.shell: |
        curl -sL https://rpm.nodesource.com/setup_lts.x | sudo bash -
        sudo yum install -y nodejs
  args:
    executable: /bin/bash