- name: Setup Node.js repository
  ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

- name: Install Node.js and its dependencies
  ansible.builtin.yum:
    name: nodejs
    state: installed